export const blogs = [
    {
        slug: "sip-ne-sampatti-kashi-vadhvavi",
        category: "म्युच्युअल फंड",
        title: "SIP ने संपत्ती कशी वाढवावी?",
        date: "12 डिसेंबर 2025",
        author: "Parth Jathar",
        blogimage: "/Calculators/Emergency.jpg",
        information : "SIP (Systematic Investment Plan) ही एक प्रभावी गुंतवणूक पद्धत आहे ज्याद्वारे नियमित मासिक रक्कम म्युच्युअल फंडात गुंतवली जाते. SIP च्या माध्यमातून गुंतवणूकदारांना बाजारातील चढ-उतारांपासून बचाव करता येतो आणि दीर्घकालीन संपत्ती निर्माण करण्यास मदत होते.",
        iamge1: "/Calculators/Emergency.jpg",
        iamge2: "/Calculators/Emergency.jpg",
        iamge3: "/Calculators/Emergency.jpg",
    },
    {
        slug: "aapatkalin-nidhi-kiti-asava",
        category: "आर्थिक नियोजन",
        title: "आपत्कालीन निधी किती असावा?",
        date: "08 डिसेंबर 2025",
        author: "Parth Jathar",
        blogimage: "/Blogs/blog2.jpg",
    },
    {
        slug: "joakhim-profile-kase-tharvave",
        category: "गुंतवणूक",
        title: "जोखीम प्रोफाइल कसे ठरवावे?",
        date: "01 डिसेंबर 2025",
        author: "Parth Jathar",
        blogimage: "/Blogs/blog3.jpg",
    },
    {
        slug: "nivrutti-guntavnuk-niyojan",
        category: "निवृत्ती नियोजन",
        title: "निवृत्तीसाठी योग्य गुंतवणूक कशी निवडावी?",
        date: "20 नोव्हेंबर 2025",
        author: "Parth Jathar",
        blogimage: "/Blogs/blog4.jpg",
    },
    {
        slug: "kar-niyojan-kase-kara",
        category: "कर नियोजन",
        title: "कर वाचवण्यासाठी योग्य गुंतवणूक कोणती?",
        date: "18 नोव्हेंबर 2025",
        author: "Parth Jathar",
        blogimage: "/Blogs/blog5.jpg",
    },
    {
        slug: "term-insurance-ka-avashyak",
        category: "इन्शुरन्स",
        title: "टर्म इन्शुरन्स का आवश्यक आहे?",
        date: "10 नोव्हेंबर 2025",
        author: "Parth Jathar",
        blogimage: "/Blogs/blog6.jpg",
    },
];